//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.webServerNW {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Proyecto EDDSoap", Namespace="http://localhost/NavalWar", ConfigurationName="webServerNW.ProyectoEDDSoap")]
    public interface ProyectoEDDSoap {
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://localhost/NavalWar is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/Administrador", ReplyAction="*")]
        GameClient.webServerNW.AdministradorResponse Administrador(GameClient.webServerNW.AdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/Administrador", ReplyAction="*")]
        System.Threading.Tasks.Task<GameClient.webServerNW.AdministradorResponse> AdministradorAsync(GameClient.webServerNW.AdministradorRequest request);
        
        // CODEGEN: Generating message contract since element name path from namespace http://localhost/NavalWar is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/UpFileUsers", ReplyAction="*")]
        GameClient.webServerNW.UpFileUsersResponse UpFileUsers(GameClient.webServerNW.UpFileUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/UpFileUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<GameClient.webServerNW.UpFileUsersResponse> UpFileUsersAsync(GameClient.webServerNW.UpFileUsersRequest request);
        
        // CODEGEN: Generating message contract since element name path from namespace http://localhost/NavalWar is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/UpFileGames", ReplyAction="*")]
        GameClient.webServerNW.UpFileGamesResponse UpFileGames(GameClient.webServerNW.UpFileGamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/UpFileGames", ReplyAction="*")]
        System.Threading.Tasks.Task<GameClient.webServerNW.UpFileGamesResponse> UpFileGamesAsync(GameClient.webServerNW.UpFileGamesRequest request);
        
        // CODEGEN: Generating message contract since element name ViewTreeResult from namespace http://localhost/NavalWar is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/ViewTree", ReplyAction="*")]
        GameClient.webServerNW.ViewTreeResponse ViewTree(GameClient.webServerNW.ViewTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/ViewTree", ReplyAction="*")]
        System.Threading.Tasks.Task<GameClient.webServerNW.ViewTreeResponse> ViewTreeAsync(GameClient.webServerNW.ViewTreeRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://localhost/NavalWar is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/AddNewUser", ReplyAction="*")]
        GameClient.webServerNW.AddNewUserResponse AddNewUser(GameClient.webServerNW.AddNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/AddNewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<GameClient.webServerNW.AddNewUserResponse> AddNewUserAsync(GameClient.webServerNW.AddNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://localhost/NavalWar is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/DeleteUser", ReplyAction="*")]
        GameClient.webServerNW.DeleteUserResponse DeleteUser(GameClient.webServerNW.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<GameClient.webServerNW.DeleteUserResponse> DeleteUserAsync(GameClient.webServerNW.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getHeigth", ReplyAction="*")]
        int getHeigth();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getHeigth", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getHeigthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getLevels", ReplyAction="*")]
        int getLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getLevels", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getLevelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getLeaves", ReplyAction="*")]
        int getLeaves();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getLeaves", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getLeavesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getBranches", ReplyAction="*")]
        int getBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/getBranches", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getBranchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/graphTree", ReplyAction="*")]
        void graphTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/graphTree", ReplyAction="*")]
        System.Threading.Tasks.Task graphTreeAsync();
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://localhost/NavalWar is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/IngresoUsuario", ReplyAction="*")]
        GameClient.webServerNW.IngresoUsuarioResponse IngresoUsuario(GameClient.webServerNW.IngresoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/NavalWar/IngresoUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<GameClient.webServerNW.IngresoUsuarioResponse> IngresoUsuarioAsync(GameClient.webServerNW.IngresoUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Administrador", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.AdministradorRequestBody Body;
        
        public AdministradorRequest() {
        }
        
        public AdministradorRequest(GameClient.webServerNW.AdministradorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class AdministradorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AdministradorRequestBody() {
        }
        
        public AdministradorRequestBody(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdministradorResponse", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.AdministradorResponseBody Body;
        
        public AdministradorResponse() {
        }
        
        public AdministradorResponse(GameClient.webServerNW.AdministradorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class AdministradorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdministradorResult;
        
        public AdministradorResponseBody() {
        }
        
        public AdministradorResponseBody(bool AdministradorResult) {
            this.AdministradorResult = AdministradorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpFileUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpFileUsers", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.UpFileUsersRequestBody Body;
        
        public UpFileUsersRequest() {
        }
        
        public UpFileUsersRequest(GameClient.webServerNW.UpFileUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class UpFileUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public UpFileUsersRequestBody() {
        }
        
        public UpFileUsersRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpFileUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpFileUsersResponse", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.UpFileUsersResponseBody Body;
        
        public UpFileUsersResponse() {
        }
        
        public UpFileUsersResponse(GameClient.webServerNW.UpFileUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpFileUsersResponseBody {
        
        public UpFileUsersResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpFileGamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpFileGames", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.UpFileGamesRequestBody Body;
        
        public UpFileGamesRequest() {
        }
        
        public UpFileGamesRequest(GameClient.webServerNW.UpFileGamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class UpFileGamesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public UpFileGamesRequestBody() {
        }
        
        public UpFileGamesRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpFileGamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpFileGamesResponse", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.UpFileGamesResponseBody Body;
        
        public UpFileGamesResponse() {
        }
        
        public UpFileGamesResponse(GameClient.webServerNW.UpFileGamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpFileGamesResponseBody {
        
        public UpFileGamesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewTreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewTree", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.ViewTreeRequestBody Body;
        
        public ViewTreeRequest() {
        }
        
        public ViewTreeRequest(GameClient.webServerNW.ViewTreeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ViewTreeRequestBody {
        
        public ViewTreeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewTreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewTreeResponse", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.ViewTreeResponseBody Body;
        
        public ViewTreeResponse() {
        }
        
        public ViewTreeResponse(GameClient.webServerNW.ViewTreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class ViewTreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ViewTreeResult;
        
        public ViewTreeResponseBody() {
        }
        
        public ViewTreeResponseBody(string ViewTreeResult) {
            this.ViewTreeResult = ViewTreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewUser", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.AddNewUserRequestBody Body;
        
        public AddNewUserRequest() {
        }
        
        public AddNewUserRequest(GameClient.webServerNW.AddNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class AddNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int conectado;
        
        public AddNewUserRequestBody() {
        }
        
        public AddNewUserRequestBody(string nickname, string password, string email, int conectado) {
            this.nickname = nickname;
            this.password = password;
            this.email = email;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewUserResponse", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.AddNewUserResponseBody Body;
        
        public AddNewUserResponse() {
        }
        
        public AddNewUserResponse(GameClient.webServerNW.AddNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddNewUserResponseBody {
        
        public AddNewUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(GameClient.webServerNW.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(GameClient.webServerNW.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteUserResponseBody {
        
        public DeleteUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresoUsuario", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.IngresoUsuarioRequestBody Body;
        
        public IngresoUsuarioRequest() {
        }
        
        public IngresoUsuarioRequest(GameClient.webServerNW.IngresoUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class IngresoUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public IngresoUsuarioRequestBody() {
        }
        
        public IngresoUsuarioRequestBody(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresoUsuarioResponse", Namespace="http://localhost/NavalWar", Order=0)]
        public GameClient.webServerNW.IngresoUsuarioResponseBody Body;
        
        public IngresoUsuarioResponse() {
        }
        
        public IngresoUsuarioResponse(GameClient.webServerNW.IngresoUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/NavalWar")]
    public partial class IngresoUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IngresoUsuarioResult;
        
        public IngresoUsuarioResponseBody() {
        }
        
        public IngresoUsuarioResponseBody(bool IngresoUsuarioResult) {
            this.IngresoUsuarioResult = IngresoUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProyectoEDDSoapChannel : GameClient.webServerNW.ProyectoEDDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProyectoEDDSoapClient : System.ServiceModel.ClientBase<GameClient.webServerNW.ProyectoEDDSoap>, GameClient.webServerNW.ProyectoEDDSoap {
        
        public ProyectoEDDSoapClient() {
        }
        
        public ProyectoEDDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProyectoEDDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectoEDDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectoEDDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameClient.webServerNW.AdministradorResponse GameClient.webServerNW.ProyectoEDDSoap.Administrador(GameClient.webServerNW.AdministradorRequest request) {
            return base.Channel.Administrador(request);
        }
        
        public bool Administrador(string nickname, string password) {
            GameClient.webServerNW.AdministradorRequest inValue = new GameClient.webServerNW.AdministradorRequest();
            inValue.Body = new GameClient.webServerNW.AdministradorRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            GameClient.webServerNW.AdministradorResponse retVal = ((GameClient.webServerNW.ProyectoEDDSoap)(this)).Administrador(inValue);
            return retVal.Body.AdministradorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameClient.webServerNW.AdministradorResponse> GameClient.webServerNW.ProyectoEDDSoap.AdministradorAsync(GameClient.webServerNW.AdministradorRequest request) {
            return base.Channel.AdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.webServerNW.AdministradorResponse> AdministradorAsync(string nickname, string password) {
            GameClient.webServerNW.AdministradorRequest inValue = new GameClient.webServerNW.AdministradorRequest();
            inValue.Body = new GameClient.webServerNW.AdministradorRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            return ((GameClient.webServerNW.ProyectoEDDSoap)(this)).AdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameClient.webServerNW.UpFileUsersResponse GameClient.webServerNW.ProyectoEDDSoap.UpFileUsers(GameClient.webServerNW.UpFileUsersRequest request) {
            return base.Channel.UpFileUsers(request);
        }
        
        public void UpFileUsers(string path) {
            GameClient.webServerNW.UpFileUsersRequest inValue = new GameClient.webServerNW.UpFileUsersRequest();
            inValue.Body = new GameClient.webServerNW.UpFileUsersRequestBody();
            inValue.Body.path = path;
            GameClient.webServerNW.UpFileUsersResponse retVal = ((GameClient.webServerNW.ProyectoEDDSoap)(this)).UpFileUsers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameClient.webServerNW.UpFileUsersResponse> GameClient.webServerNW.ProyectoEDDSoap.UpFileUsersAsync(GameClient.webServerNW.UpFileUsersRequest request) {
            return base.Channel.UpFileUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.webServerNW.UpFileUsersResponse> UpFileUsersAsync(string path) {
            GameClient.webServerNW.UpFileUsersRequest inValue = new GameClient.webServerNW.UpFileUsersRequest();
            inValue.Body = new GameClient.webServerNW.UpFileUsersRequestBody();
            inValue.Body.path = path;
            return ((GameClient.webServerNW.ProyectoEDDSoap)(this)).UpFileUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameClient.webServerNW.UpFileGamesResponse GameClient.webServerNW.ProyectoEDDSoap.UpFileGames(GameClient.webServerNW.UpFileGamesRequest request) {
            return base.Channel.UpFileGames(request);
        }
        
        public void UpFileGames(string path) {
            GameClient.webServerNW.UpFileGamesRequest inValue = new GameClient.webServerNW.UpFileGamesRequest();
            inValue.Body = new GameClient.webServerNW.UpFileGamesRequestBody();
            inValue.Body.path = path;
            GameClient.webServerNW.UpFileGamesResponse retVal = ((GameClient.webServerNW.ProyectoEDDSoap)(this)).UpFileGames(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameClient.webServerNW.UpFileGamesResponse> GameClient.webServerNW.ProyectoEDDSoap.UpFileGamesAsync(GameClient.webServerNW.UpFileGamesRequest request) {
            return base.Channel.UpFileGamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.webServerNW.UpFileGamesResponse> UpFileGamesAsync(string path) {
            GameClient.webServerNW.UpFileGamesRequest inValue = new GameClient.webServerNW.UpFileGamesRequest();
            inValue.Body = new GameClient.webServerNW.UpFileGamesRequestBody();
            inValue.Body.path = path;
            return ((GameClient.webServerNW.ProyectoEDDSoap)(this)).UpFileGamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameClient.webServerNW.ViewTreeResponse GameClient.webServerNW.ProyectoEDDSoap.ViewTree(GameClient.webServerNW.ViewTreeRequest request) {
            return base.Channel.ViewTree(request);
        }
        
        public string ViewTree() {
            GameClient.webServerNW.ViewTreeRequest inValue = new GameClient.webServerNW.ViewTreeRequest();
            inValue.Body = new GameClient.webServerNW.ViewTreeRequestBody();
            GameClient.webServerNW.ViewTreeResponse retVal = ((GameClient.webServerNW.ProyectoEDDSoap)(this)).ViewTree(inValue);
            return retVal.Body.ViewTreeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameClient.webServerNW.ViewTreeResponse> GameClient.webServerNW.ProyectoEDDSoap.ViewTreeAsync(GameClient.webServerNW.ViewTreeRequest request) {
            return base.Channel.ViewTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.webServerNW.ViewTreeResponse> ViewTreeAsync() {
            GameClient.webServerNW.ViewTreeRequest inValue = new GameClient.webServerNW.ViewTreeRequest();
            inValue.Body = new GameClient.webServerNW.ViewTreeRequestBody();
            return ((GameClient.webServerNW.ProyectoEDDSoap)(this)).ViewTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameClient.webServerNW.AddNewUserResponse GameClient.webServerNW.ProyectoEDDSoap.AddNewUser(GameClient.webServerNW.AddNewUserRequest request) {
            return base.Channel.AddNewUser(request);
        }
        
        public void AddNewUser(string nickname, string password, string email, int conectado) {
            GameClient.webServerNW.AddNewUserRequest inValue = new GameClient.webServerNW.AddNewUserRequest();
            inValue.Body = new GameClient.webServerNW.AddNewUserRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            GameClient.webServerNW.AddNewUserResponse retVal = ((GameClient.webServerNW.ProyectoEDDSoap)(this)).AddNewUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameClient.webServerNW.AddNewUserResponse> GameClient.webServerNW.ProyectoEDDSoap.AddNewUserAsync(GameClient.webServerNW.AddNewUserRequest request) {
            return base.Channel.AddNewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.webServerNW.AddNewUserResponse> AddNewUserAsync(string nickname, string password, string email, int conectado) {
            GameClient.webServerNW.AddNewUserRequest inValue = new GameClient.webServerNW.AddNewUserRequest();
            inValue.Body = new GameClient.webServerNW.AddNewUserRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            return ((GameClient.webServerNW.ProyectoEDDSoap)(this)).AddNewUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameClient.webServerNW.DeleteUserResponse GameClient.webServerNW.ProyectoEDDSoap.DeleteUser(GameClient.webServerNW.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public void DeleteUser(string nickname) {
            GameClient.webServerNW.DeleteUserRequest inValue = new GameClient.webServerNW.DeleteUserRequest();
            inValue.Body = new GameClient.webServerNW.DeleteUserRequestBody();
            inValue.Body.nickname = nickname;
            GameClient.webServerNW.DeleteUserResponse retVal = ((GameClient.webServerNW.ProyectoEDDSoap)(this)).DeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameClient.webServerNW.DeleteUserResponse> GameClient.webServerNW.ProyectoEDDSoap.DeleteUserAsync(GameClient.webServerNW.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.webServerNW.DeleteUserResponse> DeleteUserAsync(string nickname) {
            GameClient.webServerNW.DeleteUserRequest inValue = new GameClient.webServerNW.DeleteUserRequest();
            inValue.Body = new GameClient.webServerNW.DeleteUserRequestBody();
            inValue.Body.nickname = nickname;
            return ((GameClient.webServerNW.ProyectoEDDSoap)(this)).DeleteUserAsync(inValue);
        }
        
        public int getHeigth() {
            return base.Channel.getHeigth();
        }
        
        public System.Threading.Tasks.Task<int> getHeigthAsync() {
            return base.Channel.getHeigthAsync();
        }
        
        public int getLevels() {
            return base.Channel.getLevels();
        }
        
        public System.Threading.Tasks.Task<int> getLevelsAsync() {
            return base.Channel.getLevelsAsync();
        }
        
        public int getLeaves() {
            return base.Channel.getLeaves();
        }
        
        public System.Threading.Tasks.Task<int> getLeavesAsync() {
            return base.Channel.getLeavesAsync();
        }
        
        public int getBranches() {
            return base.Channel.getBranches();
        }
        
        public System.Threading.Tasks.Task<int> getBranchesAsync() {
            return base.Channel.getBranchesAsync();
        }
        
        public void graphTree() {
            base.Channel.graphTree();
        }
        
        public System.Threading.Tasks.Task graphTreeAsync() {
            return base.Channel.graphTreeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameClient.webServerNW.IngresoUsuarioResponse GameClient.webServerNW.ProyectoEDDSoap.IngresoUsuario(GameClient.webServerNW.IngresoUsuarioRequest request) {
            return base.Channel.IngresoUsuario(request);
        }
        
        public bool IngresoUsuario(string nickname, string password) {
            GameClient.webServerNW.IngresoUsuarioRequest inValue = new GameClient.webServerNW.IngresoUsuarioRequest();
            inValue.Body = new GameClient.webServerNW.IngresoUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            GameClient.webServerNW.IngresoUsuarioResponse retVal = ((GameClient.webServerNW.ProyectoEDDSoap)(this)).IngresoUsuario(inValue);
            return retVal.Body.IngresoUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameClient.webServerNW.IngresoUsuarioResponse> GameClient.webServerNW.ProyectoEDDSoap.IngresoUsuarioAsync(GameClient.webServerNW.IngresoUsuarioRequest request) {
            return base.Channel.IngresoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.webServerNW.IngresoUsuarioResponse> IngresoUsuarioAsync(string nickname, string password) {
            GameClient.webServerNW.IngresoUsuarioRequest inValue = new GameClient.webServerNW.IngresoUsuarioRequest();
            inValue.Body = new GameClient.webServerNW.IngresoUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            return ((GameClient.webServerNW.ProyectoEDDSoap)(this)).IngresoUsuarioAsync(inValue);
        }
    }
}
